package dev.flashflow.shared;

public enum OrderAttemptOutcome {
    STARTED,
    OPTIMISTIC_CONFLICT,
    TRANSIENT_DATABASE_RETRY,
    CLAIM_RACE_ROLLBACK,
    CLAIM_RACE_REPLAY,
    CLAIM_RACE_EXHAUSTED,
    RETRY_EXHAUSTED,
    CONNECTION_POOL_ACQUISITION_FAILURE,
    UNEXPECTED_FAILURE
}
