brokerClusterName=FlashFlowSpike
brokerName=flashflow-broker
brokerId=0
brokerIP1=127.0.0.1
brokerRole=ASYNC_MASTER
flushDiskType=SYNC_FLUSH
listenPort=10911
autoCreateTopicEnable=false
deleteWhen=04
fileReservedTime=1
storePathRootDir=/home/rocketmq/store
