package dev.flashflow.messaging.spike;

public enum MessagingSpikeFault {
    NONE,
    DEFINITIVE_PUBLISH_FAILURE,
    LOST_PRODUCER_RESPONSE,
    DUPLICATE_DELIVERY,
    CONSUMER_BEFORE_COMMIT,
    CONSUMER_AFTER_COMMIT_BEFORE_ACK,
    ACKNOWLEDGEMENT_LOSS,
    BROKER_RESTART,
    DELAYED_REDELIVERY,
    UNSUPPORTED_ENVELOPE,
    POISON_ENVELOPE
}
